# Generated by Django 5.1.7 on 2026-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_alert_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_tokens',
            field=models.JSONField(blank=True, default=list, help_text='FCM device tokens for push notifications'),
        ),
    ]
