# Generated by Django 5.1.7 on 2026-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_fcm_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geofence_history',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks geofence entries and notification timestamps. Format: {'geofence_id': 'ISO_timestamp'}"),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.JSONField(blank=True, help_text="User's current location (longitude, latitude)", null=True),
        ),
    ]
