# Generated by Django 5.1.7 on 2026-04-03 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0011_officeralert_alertread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'security_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='duty_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty Session',
                'verbose_name_plural': 'Duty Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
