"""
Django settings for main_admin_panel project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Try to load dotenv, but don't fail if it's not installed
try:
    from dotenv import load_dotenv
    load_dotenv()
except ModuleNotFoundError:
    # dotenv is optional - environment variables can be set directly
    def load_dotenv(*_args, **_kwargs):
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# REMOVED: Unused database_url variable
# Database configuration is handled below using dj_database_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-5xl4(8z1!y&+nsci$=!@nax_@)ls&dd4m2g+vfzv@g7vpjnws&")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,10.0.2.2').split(',')
ALLOWED_HOSTS.append('safetnet.onrender.com')
ALLOWED_HOSTS.append('safetnet-backend.onrender.com')
ALLOWED_HOSTS.append('192.168.0.125')  # Local network IP for device testing
ALLOWED_HOSTS.append('192.168.1.26')   # Your current IP for device testing
ALLOWED_HOSTS.append('192.168.0.100')   # Current machine IP for Android device

# Add Render domain if on Render
if os.getenv('RENDER'):
    ALLOWED_HOSTS.append(os.getenv('RENDER_EXTERNAL_URL', '').replace('https://', ''))

print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"RENDER environment: {os.getenv('RENDER')}")
print(f"DATABASE_URL present: {bool(os.getenv('DATABASE_URL'))}")
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "django_extensions",
    #Custom Apps
    "users",
    "users_profile",
    "core",
    "security_app",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RemoveCOOPHeaderMiddleware",  # Remove COOP header in DEBUG mode
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SafeTNet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SafeTNet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# REMOVED: Old hardcoded database configuration
# All database configuration now uses DATABASE_URL environment variable only



# Database configuration - Optimized for Neon PostgreSQL with SSL
# Database configuration for different environments
def get_database_config():
    """
    Configure database based on environment.
    - Always use PostgreSQL via DATABASE_URL for multi-platform support
    - Fallback to Neon PostgreSQL if DATABASE_URL is not set
    """
    # Check if we're on Render (has RENDER environment variable)
    is_render = os.getenv('RENDER') is not None or os.getenv('RENDER_SERVICE_ID') is not None
    database_url = os.getenv('DATABASE_URL')

    # Debug environment info (only in DEBUG mode to avoid log spam in production)
    if DEBUG:
        print(f"Environment check:")
        print(f"   DEBUG: {DEBUG}")
        print(f"   RENDER: {is_render}")
        print(f"   RENDER_SERVICE_ID: {os.getenv('RENDER_SERVICE_ID')}")
        print(f"   DATABASE_URL present: {bool(database_url)}")

        if database_url:
            print(f"Using DATABASE_URL: {database_url[:50]}...")
        else:
            print("No DATABASE_URL found, using fallback Neon config")

    # Always use PostgreSQL for multi-platform support
    if database_url:
        print("Configuring PostgreSQL from DATABASE_URL")
        try:
            db_config = dj_database_url.parse(database_url, conn_max_age=600, ssl_require=True)
            print(f"Database config parsed successfully")
            print(f"   Engine: {db_config.get('ENGINE', 'Unknown')}")
            print(f"   Host: {db_config.get('HOST', 'Unknown')}")
            print(f"   Name: {db_config.get('NAME', 'Unknown')}")
            return db_config
        except Exception as e:
            print(f"Error parsing DATABASE_URL: {e}")
            # Continue to fallback configuration
    else:
        print("DATABASE_URL not found, using fallback Neon PostgreSQL config")

    # Fallback Neon PostgreSQL configuration
    print("Using fallback Neon PostgreSQL configuration")
    return dj_database_url.parse(
        'postgresql://neondb_owner:npg_Q6V0LwCybNvY@ep-red-queen-ahjbhshv-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
        conn_max_age=600,
        ssl_require=True
    )

DATABASES = {
    'default': get_database_config(),
}

# Additional database options for Neon stability
# PostgreSQL SSL options only apply in production
if not DEBUG:
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'sslcert': None,
        'sslkey': None,
        'sslrootcert': None,
        'connect_timeout': 30,
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 5,
    }

# Print database connection details for debugging (only once and only in DEBUG mode)
if DEBUG and os.getenv('RENDER'):
    db_config = DATABASES['default']
    print("=== DATABASE CONFIGURATION (DEBUG MODE) ===")
    print(f"Database Engine: {db_config.get('ENGINE', 'Unknown')}")
    print(f"Database Name: {db_config.get('NAME', 'Unknown')}")
    print(f"Database Host: {db_config.get('HOST', 'Unknown')}")
    print(f"Database Port: {db_config.get('PORT', 'Unknown')}")
    print(f"Database User: {db_config.get('USER', 'Unknown')}")
    print(f"SSL Mode: {db_config.get('OPTIONS', {}).get('sslmode', 'Unknown')}")
    print("===========================================")




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'SafeTNet Admin Panel API',
    'DESCRIPTION': 'API for SafeTNet Main Admin Panel with Alerts and Reports',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'PERMISSION_WHITELIST': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=config('JWT_REFRESH_TOKEN_LIFETIME', default=1440, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SECRET_KEY', default=SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS Configuration
# In DEBUG mode, allow all origins for development (including live-share pages)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []  # Ignore specific origins when allowing all
else:
    CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://security-frontend-website.onrender.com",
    "https://security-app-vert.vercel.app",
    "https://security-app-veot.onrender.com",
    "https://safetnet-backend.onrender.com",
    # Allow same-origin requests for live-share pages
    "http://safetnet-backend.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests for 24 hours

# Allow all common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Proxy Configuration (for Render.com and other reverse proxies)
# Trust proxy headers for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://security-frontend-website.onrender.com",
    "https://security-app-vert.vercel.app",
    "https://security-app-veot.onrender.com",
    "https://safetnet-backend.onrender.com",
    "https://safetnet.onrender.com",
]

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Disable Cross-Origin-Opener-Policy for local development (causes browser warnings with HTTP)
# This is only needed for HTTPS in production
if DEBUG:
    # Don't set COOP header in DEBUG mode (local development with HTTP)
    pass
else:
    # In production, COOP is handled by SecurityMiddleware automatically
    pass

# Logging Configuration
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)
if os.environ.get("RENDER") == "true":  # Render sets this env variable
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': str(LOG_DIR / 'django.log'),
                'formatter': 'verbose',
            },
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'root': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
            'users': {
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': False,
            },
        },
    }
# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default=None)

# Firebase Cloud Messaging Configuration
FCM_SERVER_KEY = config('FCM_SERVER_KEY', default=None)

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='SafeTNet Admin <noreply@safetnet.com>')
SERVER_EMAIL = config('SERVER_EMAIL', default='SafeTNet Admin <noreply@safetnet.com>')

# Live share configuration (used for public tracking links)
if DEBUG:
    LIVE_SHARE_BASE_URL = config('LIVE_SHARE_BASE_URL', default='http://127.0.0.1:8000/live-share/')
else:
    LIVE_SHARE_BASE_URL = config('LIVE_SHARE_BASE_URL', default='https://safetnet-backend.onrender.com/live-share/')
