# Generated by Django 5.1.7 on 2026-01-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0022_alter_livelocationshare_security_officer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='sosevent',
                    name='audio_recording_url',
                ),
                migrations.RemoveField(
                    model_name='sosevent',
                    name='cloud_backup_url',
                ),
                migrations.RemoveField(
                    model_name='sosevent',
                    name='is_premium_event',
                ),
                migrations.RemoveField(
                    model_name='sosevent',
                    name='video_recording_url',
                ),
            ],
        ),
    ]
