# Generated by Codex on 2026-03-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0023_remove_sosevent_audio_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlaySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Android package name verified with Google Play', max_length=255)),
                ('product_id', models.CharField(blank=True, help_text='Subscription product identifier from Google Play', max_length=255)),
                ('purchase_token', models.CharField(help_text='Google Play purchase token', max_length=512, unique=True)),
                ('linked_purchase_token', models.CharField(blank=True, db_index=True, help_text='Previous token linked by Google Play for upgrades, downgrades, or re-subscribe flows', max_length=512, null=True)),
                ('latest_order_id', models.CharField(blank=True, help_text='Latest order identifier reported by Google Play', max_length=255)),
                ('subscription_state', models.CharField(blank=True, help_text='Latest subscription lifecycle state from Google Play', max_length=64)),
                ('acknowledgement_state', models.CharField(blank=True, help_text='Acknowledgement state returned by Google Play', max_length=64)),
                ('auto_renew_enabled', models.BooleanField(default=False, help_text='Whether the subscription is currently set to auto-renew')),
                ('line_item_index', models.PositiveIntegerField(default=0, help_text='Index of the line item selected from the subscriptionsv2 response')),
                ('expiry_time', models.DateTimeField(blank=True, help_text='Expiry time reported for the selected subscription line item', null=True)),
                ('external_account_id', models.CharField(blank=True, help_text='Obfuscated external account identifier returned by Google Play', max_length=255)),
                ('external_profile_id', models.CharField(blank=True, help_text='Obfuscated external profile identifier returned by Google Play', max_length=255)),
                ('is_test_purchase', models.BooleanField(default=False, help_text='Whether Google Play reported this as a test purchase')),
                ('last_event_type', models.CharField(blank=True, help_text='Last RTDN event type processed for this token', max_length=64)),
                ('last_notification_at', models.DateTimeField(blank=True, help_text='Timestamp of the last processed RTDN event', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful verification with Google Play', null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Most recent raw subscriptionsv2 payload from Google Play')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User currently associated with this Google Play purchase token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_play_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Play Subscription',
                'verbose_name_plural': 'Google Play Subscriptions',
                'db_table': 'users_google_play_subscription',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='googleplaysubscription',
            index=models.Index(fields=['user', 'subscription_state'], name='users_googl_user_id_8145b1_idx'),
        ),
        migrations.AddIndex(
            model_name='googleplaysubscription',
            index=models.Index(fields=['product_id', 'subscription_state'], name='users_googl_product__f37ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='googleplaysubscription',
            index=models.Index(fields=['linked_purchase_token'], name='users_googl_linked__21c8c4_idx'),
        ),
    ]
