# Generated by Django 5.1.7 on 2026-03-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0024_googleplaysubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googleplaysubscription',
            new_name='users_googl_user_id_8222f0_idx',
            old_name='users_googl_user_id_8145b1_idx',
        ),
        migrations.RenameIndex(
            model_name='googleplaysubscription',
            new_name='users_googl_product_51b6e9_idx',
            old_name='users_googl_product__f37ab6_idx',
        ),
        migrations.RenameIndex(
            model_name='googleplaysubscription',
            new_name='users_googl_linked__e76acd_idx',
            old_name='users_googl_linked__21c8c4_idx',
        ),
    ]
