# Generated by Django 5.1.7 on 2026-04-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_geofence_history_user_location'),
        ('users_profile', '0025_rename_users_googl_user_id_8145b1_idx_users_googl_user_id_8222f0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='users.geofence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geofence Event',
                'verbose_name_plural': 'Geofence Events',
                'db_table': 'users_geofence_event',
                'ordering': ['-timestamp'],
            },
        ),
    ]
